# Generated by Django 2.0.2 on 2018-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time', models.DateTimeField(null=True)),
                ('revision', models.IntegerField(null=True)),
                ('book_isbn', models.CharField(max_length=64, null=True)),
                ('word_count', models.IntegerField(null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('open_type', models.CharField(max_length=20, null=True)),
                ('book_paper', models.CharField(max_length=30, null=True)),
                ('book_wrapper', models.CharField(max_length=64, null=True)),
                ('book_price', models.FloatField(null=True)),
                ('book_dprice', models.FloatField(null=True)),
                ('editor_recommendation', models.TextField(null=True)),
                ('content_introduction', models.TextField(null=True)),
                ('author_introduction', models.TextField(null=True)),
                ('menu', models.TextField(null=True)),
                ('media_review', models.TextField(null=True)),
                ('digest_image_path', models.TextField(null=True)),
                ('product_image_path', models.CharField(max_length=128, null=True)),
                ('series_name', models.CharField(max_length=128, null=True)),
                ('printing_time', models.DateTimeField(null=True)),
                ('impression', models.CharField(max_length=64, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('shelves_date', models.DateTimeField(null=True)),
                ('customer_socre', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('book_status', models.IntegerField(null=True)),
                ('sales', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('book_counts', models.IntegerField(null=True)),
                ('category_pid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_category',
                'managed': False,
            },
        ),
    ]
